name: Release

on:
  push:
    tags:
      - "v*" # Triggers on tags starting with "v"

jobs:
  release:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout the repository
      packages: write # Required to publish to GitHub Packages + Container Registry
      attestations: write # Required to publish attestations

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clone

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # Set up QEMU required by buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.2.0
        id: run-goreleaser
        with:
          version: "~> v2.8"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: ${{ github.repository_owner}}
          REPO: ${{ github.repository }}
